name: Running from GitHub with ORacle DB
on: [push, pull_request]
jobs:
  oracle-db-free:
    runs-on: ubuntu-latest
    steps:
      - uses: gvenzl/setup-oracle-free
        with:
          container-name: oracledb
          container-runtime: podman
          tag: slim
          app-user-password: manager
          app-user: system
          java-version: '17'
          distribution: 'temurin'
      - name: Run the Maven verify phase
        run: mvn --batch-mode --update-snapshots verify
